enabled: true
dropdown:
  enabled: false
footer: 'Copyright Proximax 2019. All rights reserved.'
social_twitter: ProximaXio
social_facebook: ProximaXio
social_github: proximax-storage
social_youtube: UCky9HP0VlqsnGQWrbMPFVnw
social_instagram: proximaxio
favicon:
  user/themes/haywire/images/favicon/PROXIMAX-512x512.png:
    name: PROXIMAX-512x512.png
    type: image/png
    size: 78691
    path: user/themes/haywire/images/favicon/PROXIMAX-512x512.png
