enabled: true
production-mode: true
grid-size: grid-md
header-fixed: true
header-animated: true
header-dark: true
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: true
  icons: true
custom_logo:
  'user/themes/quark/images/logo/181102_ProximaX Logo Colour.png':
    name: '181102_ProximaX Logo Colour.png'
    type: image/png
    size: 8146
    path: 'user/themes/quark/images/logo/181102_ProximaX Logo Colour.png'
