version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1539287726
layout:
  /navigation/:
    -
      - 'logo-5679 25'
      - 'menu-2875 75'
  /slideshow/:
    -
      - 'position-position-5412 25'
      - 'position-position-9298 25'
      - 'position-position-5357 25'
      - 'position-position-7358 25'
  /topfullwidth/:
    -
      - position-position-7023
  /top/:
    -
      - 'position-position-5939 25'
      - 'position-position-7490 25'
      - 'position-position-2336 25'
      - 'position-position-7291 25'
  /showcase/:
    -
      - 'position-position-2621 25'
      - 'position-position-4680 25'
      - 'position-position-4839 25'
      - 'position-position-1217 25'
  /breadcrumb/:
    -
      - position-position-5071
  /feature/:
    -
      - 'position-position-4543 25'
      - 'position-position-5434 25'
      - 'position-position-5489 25'
      - 'position-position-8898 25'
  /utility/:
    -
      - 'position-position-3724 25'
      - 'position-position-2653 25'
      - 'position-position-3401 25'
      - 'position-position-1491 25'
  /expandedtop/:
    -
      - 'position-position-1000 25'
      - 'position-position-7873 25'
      - 'position-position-6835 25'
      - 'position-position-3436 25'
  /maintop/:
    -
      - 'position-position-2723 25'
      - 'position-position-7137 25'
      - 'position-position-3102 25'
      - 'position-position-1823 25'
  /main/:
    -
      -
        'mainbody 60':
          -
            - system-content-6489
      -
        'sidebar 40':
          -
            - position-position-7684
  /mainbottom/:
    -
      - 'position-position-7827 25'
      - 'position-position-4155 25'
      - 'position-position-2697 25'
      - 'position-position-1720 25'
  /expandedbottom/:
    -
      - 'position-position-5349 25'
      - 'position-position-9431 25'
      - 'position-position-9746 25'
      - 'position-position-9170 25'
  /fullwidth/:
    -
      - position-position-3944
  /extension/:
    -
      - 'position-position-3769 25'
      - 'position-position-2063 25'
      - 'position-position-6577 25'
      - 'position-position-1027 25'
  /bottom/:
    -
      - 'position-position-2796 25'
      - 'position-position-7267 25'
      - 'position-position-5690 25'
      - 'position-position-7655 25'
  /footer/:
    -
      - 'position-position-4077 25'
      - 'position-position-4480 25'
      - 'position-position-9100 25'
      - 'position-position-6570 25'
  /copyright/:
    -
      - 'branding-4483 33'
      - 'totop-7311 34'
      - 'social-8525 33'
  offcanvas:
    -
      - mobile-menu-4892
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  slideshow:
    type: section
    attributes:
      boxed: ''
      class: ''
  topfullwidth:
    type: section
    title: TopFullWidth
    attributes:
      boxed: ''
      class: ''
  top:
    type: section
    attributes:
      boxed: ''
      class: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      class: ''
  breadcrumb:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
      class: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  expandedtop:
    type: section
    attributes:
      boxed: ''
      class: ''
  maintop:
    type: section
    attributes:
      boxed: ''
      class: ''
  mainbody:
    type: section
  sidebar:
    type: section
  main:
    type: container
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  mainbottom:
    type: section
    attributes:
      boxed: ''
      class: ''
  expandedbottom:
    type: section
    attributes:
      boxed: ''
      class: ''
  fullwidth:
    type: section
    title: FullWidth
    attributes:
      boxed: ''
      class: ''
  extension:
    type: section
    attributes:
      boxed: ''
      class: ''
  bottom:
    type: section
    attributes:
      boxed: ''
      class: ''
  footer:
    attributes:
      boxed: ''
      class: ''
  copyright:
    type: section
    attributes:
      boxed: ''
      class: ''
  offcanvas:
    attributes:
      position: g-offcanvas-left
      class: ''
      extra: {  }
      swipe: '0'
      css3animation: '1'
content:
  logo-5679:
    attributes:
      image: 'gantry-media://logo/logo.png'
      class: g-logo
    block:
      variations: nomarginall
  menu-2875:
    block:
      class: g-chimera-menu
      variations: 'center nomarginall nopaddingall'
  position-position-5412:
    title: 'Slideshow A'
    attributes:
      key: slideshow-a
  position-position-9298:
    title: 'Slideshow B'
    attributes:
      key: slideshow-b
  position-position-5357:
    title: 'Slideshow C'
    attributes:
      key: slideshow-c
  position-position-7358:
    title: 'Slideshow D'
    attributes:
      key: slideshow-d
  position-position-7023:
    title: 'Top Fullwidth'
    attributes:
      key: topfullwidth
  position-position-5939:
    title: 'Top A'
    attributes:
      key: top-a
  position-position-7490:
    title: 'Top B'
    attributes:
      key: top-b
  position-position-2336:
    title: 'Top C'
    attributes:
      key: top-c
  position-position-7291:
    title: 'Top D'
    attributes:
      key: top-d
  position-position-2621:
    title: 'Showcase A'
    attributes:
      key: showcase-a
  position-position-4680:
    title: 'Showcase B'
    attributes:
      key: showcase-b
  position-position-4839:
    title: 'Showcase C'
    attributes:
      key: showcase-c
  position-position-1217:
    title: 'Showcase D'
    attributes:
      key: showcase-d
  position-position-5071:
    title: Breadcrumb
    attributes:
      key: breadcrumb
  position-position-4543:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-position-5434:
    title: 'Feature B'
    attributes:
      key: feature-b
  position-position-5489:
    title: 'Feature C'
    attributes:
      key: feature-c
  position-position-8898:
    title: 'Feature D'
    attributes:
      key: feature-d
  position-position-3724:
    title: 'Utility A'
    attributes:
      key: utility-a
  position-position-2653:
    title: 'Utility B'
    attributes:
      key: utility-b
  position-position-3401:
    title: 'Utility C'
    attributes:
      key: utility-c
  position-position-1491:
    title: 'Utility D'
    attributes:
      key: utility-d
  position-position-1000:
    title: 'ExpandedTop A'
    attributes:
      key: expandedtop-a
  position-position-7873:
    title: 'ExpandedTop B'
    attributes:
      key: expandedtop-b
  position-position-6835:
    title: 'ExpandedTop C'
    attributes:
      key: expandedtop-c
  position-position-3436:
    title: 'ExpandedTop D'
    attributes:
      key: expandedtop-d
  position-position-2723:
    title: 'Maintop A'
    attributes:
      key: maintop-a
  position-position-7137:
    title: 'MainTop B'
    attributes:
      key: maintop-b
  position-position-3102:
    title: 'MainTop C'
    attributes:
      key: maintop-c
  position-position-1823:
    title: 'MainTop D'
    attributes:
      key: maintop-d
  position-position-7684:
    title: 'Sidebar A'
    attributes:
      key: sidebar-a
  position-position-7827:
    title: 'MainBottom A'
    attributes:
      key: mainbottom-a
  position-position-4155:
    title: 'MainBottom B'
    attributes:
      key: mainbottom-b
  position-position-2697:
    title: 'MainBottom C'
    attributes:
      key: mainbottom-c
  position-position-1720:
    title: 'MainBottom D'
    attributes:
      key: mainbottom-d
  position-position-5349:
    title: 'ExpandedBottom A'
    attributes:
      key: expandedbottom-a
  position-position-9431:
    title: 'ExpandedBottom B'
    attributes:
      key: expandedbottom-b
  position-position-9746:
    title: 'ExpandedBottom C'
    attributes:
      key: expandedbottom-c
  position-position-9170:
    title: 'ExpandedBottom D'
    attributes:
      key: expandedbottom-d
  position-position-3944:
    title: Fullwidth
    attributes:
      key: fullwidth
  position-position-3769:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-position-2063:
    title: 'Extension B'
    attributes:
      key: extension-b
  position-position-6577:
    title: 'Extension C'
    attributes:
      key: extension-c
  position-position-1027:
    title: 'Extension D'
    attributes:
      key: extension-d
  position-position-2796:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  position-position-7267:
    title: 'Bottom B'
    attributes:
      key: bottom-b
  position-position-5690:
    title: 'Bottom C'
    attributes:
      key: bottom-c
  position-position-7655:
    title: 'Bottom D'
    attributes:
      key: bottom-d
  position-position-4077:
    title: 'Footer A'
    attributes:
      key: footer-a
  position-position-4480:
    title: 'Footer B'
    attributes:
      key: footer-b
  position-position-9100:
    title: 'Footer C'
    attributes:
      key: footer-c
  position-position-6570:
    title: 'Footer D'
    attributes:
      key: footer-d
  branding-4483:
    attributes:
      content: '<a href="https://rockettheme.com/" title="RocketTheme" class="rt-powered-by"></a>'
    block:
      variations: 'smallpaddingtop smallpaddingbottom'
      extra:
        -
          data-aos: fade-right
        -
          data-aos-delay: '300'
        -
          data-aos-anchor: '#g-copyright'
        -
          data-aos-anchor-placement: bottom-bottom
  totop-7311:
    title: 'To Top'
    attributes:
      css:
        class: ''
    block:
      variations: 'smallpaddingtop smallpaddingbottom center'
      extra:
        -
          data-aos: fade-up
        -
          data-aos-delay: '300'
        -
          data-aos-anchor: '#g-copyright'
        -
          data-aos-anchor-placement: bottom-bottom
  social-8525:
    attributes:
      css:
        class: ''
    block:
      variations: 'smallpaddingbottom smallpaddingtop'
      extra:
        -
          data-aos: fade-left
        -
          data-aos-delay: '300'
        -
          data-aos-anchor: '#g-copyright'
        -
          data-aos-anchor-placement: bottom-bottom
  mobile-menu-4892:
    title: 'Mobile Menu'
