version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1446545424
layout:
  /top/:
    -
      - system-messages-2777
  /navigation/:
    -
      - 'position-position-9886 10'
      - 'menu-6934 80'
      - 'position-position-6679 10'
  /header/: {  }
  /showcase/: {  }
  /above/: {  }
  /utility/: {  }
  /feature/: {  }
  /container-5169/:
    -
      -
        'sidebar 20':
          -
            - position-position-1082
      -
        'mainbar 60':
          -
            - system-content-1050
      -
        'aside 20':
          -
            - position-position-9839
  /expanded/: {  }
  /extension/: {  }
  /bottom/: {  }
  /footer/: {  }
  /copyright/:
    -
      - 'branding-3234 33.3'
      - 'copyright-7141 33.3'
      - 'totop-7016 33.3'
  /fixedside/:
    -
      - logo-7684
    -
      - social-9373
  offcanvas:
    -
      - mobile-menu-2145
structure:
  top:
    type: section
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      class: 'box-darkgrey g-outer-box'
  above:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
  mainbar:
    type: section
  container-5169:
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  extension:
    type: section
    attributes:
      boxed: ''
  bottom:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
  fixedside:
    type: section
    title: FixedSide
    attributes:
      boxed: ''
content:
  system-messages-2777:
    block:
      variations: 'nomarginall nopaddingall'
  position-position-9886:
    title: 'MainNav Left'
    attributes:
      key: mainnav-left
    block:
      class: mainnav-left
  menu-6934:
    block:
      class: mainnav-center
  position-position-6679:
    title: 'MainNav Right'
    attributes:
      key: mainnav-right
    block:
      class: mainnav-right
  position-position-1082:
    title: Sidebar
    attributes:
      key: sidebar
  position-position-9839:
    title: Aside
    attributes:
      key: aside
  branding-3234:
    attributes:
      content: 'Powered by <a href="http://www.gantry.org/" title="Gantry Framework" class="g-powered-by">Gantry Framework</a>'
  totop-7016:
    title: 'To Top'
    attributes:
      icon: 'fa fa-arrow-circle-o-up fa-2x'
      content: ''
  logo-7684:
    attributes:
      image: ''
      text: R
      class: g-fixedside-logo
  social-9373:
    attributes:
      css:
        class: social
      items:
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: '#'
          name: Twitter
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: '#'
          name: Facebook
        -
          icon: 'fa fa-google-plus fa-fw'
          text: ''
          link: '#'
          name: 'Google +'
        -
          icon: 'fa fa-pinterest-p fa-fw'
          text: ''
          link: '#'
          name: Pinterest
        -
          icon: 'fa fa-youtube-play fa-fw'
          text: ''
          link: '#'
          name: YouTube
        -
          icon: 'fa fa-instagram fa-fw'
          text: ''
          link: '#'
          name: Instagram
        -
          icon: 'fa fa-flickr fa-fw'
          text: ''
          link: '#'
          name: Flickr
        -
          icon: 'fa fa-vimeo fa-fw'
          text: ''
          link: '#'
          name: Vimeo
  mobile-menu-2145:
    title: 'Mobile Menu'
